const ON_USERS_LOADED = 'ON_USERS_LOADED';
const SET_TO_FIRING = 'SET_TO_FIRING';
const REMOVE_FROM_FIRING = 'REMOVE_FROM_FIRING';

export {
  ON_USERS_LOADED,
  SET_TO_FIRING,
  REMOVE_FROM_FIRING,
}
